### PR TITLE
Linux branch merged

### PR DESCRIPTION
**Pull request by scharlton2**

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I found a few mistakes, please wait until I fix them before you test.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

OK, I'll wait until you contact me again, before start testing.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I was able to get prepost-gui to compile on an Ubuntu machine (with modifications), but I wasn't able to get it to link.  The Qt that I downloaded had some dependencies that were missing on my machine.  I think it's best to install a Qt that was compiled by the Linux distribution you have, but it will limit which versions of Qt are available.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the work.

It seems that you are trying to build on ubuntu 16.04, right?

I agree that it will be simple to install Qt using apt-get, but as you've already commented, the Qt version available through apt-get will be limited. i-RIC needs Qt 5.5, and I'm not sure whether it is available through apt-get.

I'll setup ubuntu 16.04 environment by myself, and see the detail of the problem. I'll contact again.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Yes Ubuntu 16.04.3.  I have a branch with some preliminary changes (some I just commented out to get it to compile).

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm thinking of deleting my iricdev (scharlton2/iricdev) so that i-RIC/iricdev is the parent repository.  It seems that pull requests would be easier if i-RIC/iricdev is the main repository and we all each fork from it.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I think that's a good idea. It will make that the things are done in a right way.

I guess the workflow like below will work:
- Delete scharlton2/iricdev once on Github
- Fork from i-RIC/iricdev to scharlton2/iricdev
- Push your branches on your local environment to scharlton2/iricdev

My kskinoue0612/iricdev forked from i-RIC/iricdev, so I guess there will be no bad side effects.

Thanks,
Keisuke

**Pull request closed without merging**
