### PR TITLE
Linux branch merged

### PR DESCRIPTION
**Pull request by scharlton2**
Recreated pull request since previous pull request has unknown **from** repository.  I will close the previous pull request.

Scott

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

I'm testing the master branch of your repository.
I've noticed that downloading HDF5 fails because HDF group changed the URL, so I've sent pull request to you.

Talking about Qt, the version that ubuntu 16.04 installs with "qt5-default" package is 5.5.1, so I think it works. I mean, we can ask ubuntu user to install Qt through apt-get, not by downloading installer from Qt site. This is lucky. :-)

After building all libraries, I'll try to build iRIC GUI, and report you the result.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested on ubuntu 16.04, and had two problems:

## iriclib build failed

[gcc-iriclib-logs.zip](https://github.com/i-RIC/iricdev/files/1238764/gcc-iriclib-logs.zip)

## netcdf build failed

[gcc-netcdf-logs.zip](https://github.com/i-RIC/iricdev/files/1238766/gcc-netcdf-logs.zip)

Can you check the log messages, please?

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry about the HDF5 path problem, I already had it downloaded so I didn't test it correctly.  It looks like the netcdf couldn't see the HDF5 install directories.  Could it be that the hdf5 files hadn't been downloaded and therefore hadn't built and installed hdf5?  I've added additional verbosity on the iriclib build so that it'll show more extensive output.  Could you try fetching my latest and trying again?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've checked again, got some progress, but not yet completely finished. I'll report the status.

## iriclib

Thanks to your commit, I've got the verbose log message and knew the reason. The reason of the failure was that no FORTRAN compiler is installed.

So, I've installed gfortran, and the problem was fixed.
I've sent pull request to fix this.

https://github.com/scharlton2/iricdev/pull/3

## netcdf

Fixing the issues with netcdf seems to be a little complex.

At first, I noticed that on ubuntu cmake related files are not installed to lib/install/hdf5-1.8.14/debug/cmake, but lib/install/hdf5-1.8.14/debug/**share**/cmake.

I modified build-netcdf.cmake, and then HDF5 is found correctly.

Then I noticed that we need m4 to be installed, so I added the package. A fix related to this is also included in the pull request.

https://github.com/scharlton2/iricdev/pull/3

Then I tried again, and got the message that CHECK_LIBRARY_EXISTS fails. I attach the log files to this mail.

[gcc-netcdf-logs.zip](https://github.com/i-RIC/iricdev/files/1244513/gcc-netcdf-logs.zip)

Mmm, the issue seems to be harder to fix than I've expected.

Can you try and see the same thing happen in your environment?

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I hadn't realized that I had a system compiled version of HDF5 installed on my ubuntu system which netcdf was linking to.  It seems there' s an incompatibility with the cmake/hdf5/netcdf build systems.  The variable `HDF5_C_LIBRARIES` doesn't get set on the ubuntu system.

I was able to work around it by manually setting `HDF5_LIB` `HDF5_HL_LIB` and `HDF5_INCLUDE_DIR` for both windows and linux.

I think it should work for you now.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I was able to get iric to compile and link on ubuntu.  I only had to add:

    sudo apt-get install libqt5webkit5-dev

on branch:
    https://github.com/scharlton2/prepost-gui/compare/_ubuntu_16.04.3

image

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for fixing. Great news that you succeeded to build iRIC GUI on ubuntu!

Please add `libqt5webkit5-dev` to `apt-get install` target in README.md, and let's finish this issue.
After updating README.md, please merge the pull request by yourself.

Thanks,
Keisuke

**Pull request merged**
